FROM node:latest AS nodebuild

ADD . /app-src
WORKDIR /app-src

RUN rm src/.env*
RUN touch src/.env.production

ARG API_HOST
ENV VITE_API_HOST=${API_HOST}

RUN yarn install
RUN yarn build
RUN mv "./dist" /app

## STAGE 2: Production Environment ###
FROM nginx:1.23.3-alpine

RUN rm -rf /etc/nginx/conf.d
COPY [".docker/conf", "/etc/nginx"]
COPY --from=nodebuild /app/index.html /usr/share/nginx/html
ARG PUBLIC_PATH 
COPY --from=nodebuild /app /usr/share/nginx/html/${PUBLIC_PATH}
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
